root: true
extends:
  - 'eslint:recommended'
  - 'standard'
env:
  browser: true
rules:
  no-template-curly-in-string: "off"
  no-useless-return: "off"
  no-mixed-operators: "off"
  padded-blocks: ["error", "never"]
  semi: ["error", "always"]

  # Other
  no-use-before-define: [error, { functions: false, classes: false }]
  no-multiple-empty-lines: ["error", {max: 2, maxBOF: 0, maxEOF: 0}]
  no-unused-vars: ['error', {vars: 'all', varsIgnorePattern: '^_', args: 'all', argsIgnorePattern: '^_'}]
  eol-last: "error"
  generator-star-spacing: ['error', {before: false, after: true}]
  yield-star-spacing: ['error', {before: false, after: true}]
