window.jQuery = window.$ = require('jquery');

window.libs = [
  ['lodash', require('lodash')],
  ['angular', require('angular')],
  ['qs', require('qs')],
  ['ldclient-js', require('ldclient-js')],
  ['react', require('react')],
  ['prop-types', require('prop-types')],
  ['lodash/fp', require('lodash/fp')],
  ['@contentful/forma-36-react-components', require('@contentful/forma-36-react-components')],
  [
    '@contentful/forma-36-react-components/dist/alpha',
    require('@contentful/forma-36-react-components/dist/alpha')
  ],
  ['pluralize', require('pluralize')],
  ['moment', require('moment')],
  ['classnames', require('classnames')],
  ['json-stringify-safe', require('json-stringify-safe')],
  ['js-cookie', require('js-cookie')],
  ['sum-types', require('sum-types')],
  ['@contentful/forma-36-tokens', require('@contentful/forma-36-tokens')],
  ['sortablejs', require('sortablejs')],
  ['@contentful/mimetype', require('@contentful/mimetype')],
  ['kefir', require('kefir')],
  ['emotion', require('emotion')],
  ['@contentful/validation', require('@contentful/validation')],
  ['getstream', require('getstream')],
  ['pikaday', require('pikaday')],
  ['moment-timezone', require('moment-timezone')],
  ['react-redux', require('react-redux')],
  ['@contentful/asn1js', require('@contentful/asn1js')],
  ['marked', require('marked')],
  ['react-dom', require('react-dom')],
  ['mitt', require('mitt')],
  ['sum-types/caseof-eq', require('sum-types/caseof-eq')],
  ['@contentful/rich-text-links', require('@contentful/rich-text-links')],
  ['jquery', require('jquery')],
  ['react-player', require('react-player')],
  ['is-hotkey', require('is-hotkey')],
  ['react-codemirror', require('react-codemirror')],
  ['parse-github-url', require('parse-github-url')],
  ['@contentful/hostname-transformer', require('@contentful/hostname-transformer')],
  ['react-sortable-hoc', require('react-sortable-hoc')],
  ['dataloader', require('dataloader')],
  ['detect-browser', require('detect-browser')],
  ['@contentful/rich-text-types', require('@contentful/rich-text-types')],
  ['@contentful/field-editors', require('@contentful/field-editors')],
  ['lodash/debounce', require('lodash/debounce')],
  ['codemirror', require('codemirror')],
  ['lodash/throttle', require('lodash/throttle')],
  ['slate-react', require('slate-react')],
  ['slate', require('slate')],
  ['immutable', require('immutable')],
  ['fast-deep-equal', require('fast-deep-equal')],
  ['@contentful/contentful-slatejs-adapter', require('@contentful/contentful-slatejs-adapter')],
  ['json0-ot-diff', require('json0-ot-diff')],
  ['react-sticky-el', require('react-sticky-el')],
  ['@productboard/slate-edit-list', require('@productboard/slate-edit-list')],
  [
    '@contentful/rich-text-plain-text-renderer',
    require('@contentful/rich-text-plain-text-renderer')
  ],
  ['slate-html-serializer', require('slate-html-serializer')],
  ['slate-plain-serializer', require('slate-plain-serializer')],
  ['@wikifactory/slate-trailing-block', require('@wikifactory/slate-trailing-block')],
  ['react-highlight-words', require('react-highlight-words')],
  ['downshift', require('downshift')],
  ['react-click-outside', require('react-click-outside')],
  ['react-helmet', require('react-helmet')],
  ['react-modal', require('react-modal')],
  ['lodash/delay', require('lodash/delay')],
  ['flat', require('flat')],
  ['@contentful/sharejs/lib/client', require('@contentful/sharejs/lib/client')],
  ['lodash/defer', require('lodash/defer')],
  ['file-size', require('file-size')],
  ['sanitize-html', require('sanitize-html')],
  ['marked-ast', require('marked-ast')],
  ['react-animate-height', require('react-animate-height')],
  ['jquery-textrange', require('jquery-textrange')],
  ['@babel/polyfill', require('@babel/polyfill')],
  ['angular-animate', require('angular-animate')],
  ['angular-sanitize', require('angular-sanitize')],
  ['angular-ui-router', require('angular-ui-router')],
  ['element-closest', require('element-closest')],
  ['codemirror/addon/edit/closebrackets', require('codemirror/addon/edit/closebrackets')],
  ['codemirror/mode/javascript/javascript', require('codemirror/mode/javascript/javascript')],
  ['codemirror/mode/markdown/markdown', require('codemirror/mode/markdown/markdown')],
  ['codemirror/mode/xml/xml', require('codemirror/mode/xml/xml')],
  ['codemirror/addon/edit/continuelist', require('codemirror/addon/edit/continuelist')],
  ['codemirror/addon/mode/overlay', require('codemirror/addon/mode/overlay')],
  ['codemirror/mode/htmlmixed/htmlmixed', require('codemirror/mode/htmlmixed/htmlmixed')],
  ['immer', require('immer')],
  ['redux', require('redux')],
  ['path-parser', require('path-parser')],
  ['reselect', require('reselect')],
  ['redux-thunk', require('redux-thunk')],
  ['fclone', require('fclone')],
  ['@contentful/worf', require('@contentful/worf')],
  ['speakingurl', require('speakingurl')],
  ['@contentful/sharejs/lib/types/text', require('@contentful/sharejs/lib/types/text')],
  ['@contentful/sharejs/lib/types/text-api', require('@contentful/sharejs/lib/types/text-api')],
  ['@contentful/sharejs/lib/types/json', require('@contentful/sharejs/lib/types/json')],
  ['@contentful/sharejs/lib/types/json-api', require('@contentful/sharejs/lib/types/json-api')],
  ['element-resize-detector', require('element-resize-detector')],
  ['js-htmlencode', require('js-htmlencode')],
  ['rtl-detect', require('rtl-detect')],
  ['tti-polyfill', require('tti-polyfill')],
  ['@contentful/field-editor-single-line', require('@contentful/field-editor-single-line')],
  ['@contentful/field-editor-multiple-line', require('@contentful/field-editor-multiple-line')],
  ['@contentful/field-editor-shared', require('@contentful/field-editor-shared')],
  ['contentful-resolve-response', require('contentful-resolve-response')],

  ['legacy-client', require('libs/legacy_client/client.js')],
  ['saved-views-migrator', require('libs/saved-views-migrator/index.js')],
  ['angular-mocks', require('angular-mocks')],
  ['enzyme', require('enzyme')],
  ['enzyme-adapter-react-16', require('enzyme-adapter-react-16')],
  ['react-dom/test-utils', require('react-dom/test-utils')],
  ['sinon', require('sinon')]
];
