version: 2

registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: '${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}'

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
    ignore:
      - dependency-name: 'angular*'
    labels:
      - 'dependencies'
      - 'dependabot'
    open-pull-requests-limit: 5
    reviewers:
      - 'contentful/chapter-frontend'
    registries:
      - npm-registry-registry-npmjs-org
