# This configuration is further extended by
# - tools/.eslintrc.yml
# - tests/.eslintrc.yml
root: true
extends:
  - 'eslint:recommended'
  - 'standard'
  - 'plugin:react/recommended'

env:
  browser: true
parser: 'babel-eslint'
rules:
  react/display-name: "off"
  indent: "off"
  indent-legacy: [2, 2, { "SwitchCase": 1 }]
  no-template-curly-in-string: "off"

  no-useless-return: "off"
  no-mixed-operators: "off"

  padded-blocks: [2, "never"]

  semi: ["error", "always"]

  # Other
  no-use-before-define: [error, { functions: false, classes: false }]
  no-multiple-empty-lines: ["error", {max: 2, maxBOF: 0, maxEOF: 0}]
  no-unused-vars: ['error', {vars: 'all', varsIgnorePattern: '^_', args: 'all', argsIgnorePattern: '^_'}]
  eol-last: "error"
  generator-star-spacing: ['error', {before: false, after: true}]
  yield-star-spacing: ['error', {before: false, after: true}]
  require-yield: off

overrides:
- files: [ 'src/javascripts/**/*.js' ]
  excludedFiles: [ '*.es6.js' ]
  globals:
    angular: false
    _: false
    JST: false
    $: false
- files: [ '*.es6.js' ]
  # Eslint configuration for files ending in .es6.js
  globals:
    setTimeout: false
    Promise: false
  parserOptions:
    ecmaVersion: 2017
    sourceType: module
  rules:
    # ES6 specific
    prefer-const: error
    no-var: error

    # We disallow everything we do not transpile with babel
    no-restricted-syntax:
    - error
    - BreakStatement
    - ContinueStatement
    - DebuggerStatement
    - EmptyStatement
    - ForStatement
    - LabeledStatement
    - MetaProperty
    - SequenceExpression
    - SwitchCase
    - SwitchStatement
    - TaggedTemplateExpression
    - UpdateExpression
    - WithStatement
