extends: standard
rules:
  padded-blocks: off
  semi: ["error", "always"]
  no-multiple-empty-lines: off
  no-unused-vars: ['error', {vars: 'all', args: 'all', argsIgnorePattern: '^_'}]
globals:
  angular: true
  _: true
  dotty: true
  JST: true
  $: true
