# This configuration is further extended by
# - tools/.eslintrc.yml
# - tests/.eslintrc.yml
root: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/react'
settings:
  react:
    version: "16.2.0"
env:
  browser: true
globals:
  setTimeout: false
  Promise: false
parser: 'babel-eslint'
rules:
  react/display-name: "off"
  no-template-curly-in-string: "off"

  no-useless-return: "off"
  no-mixed-operators: "off"

  padded-blocks: ["warn", "never"]

  # Other
  no-use-before-define: [error, { functions: false, classes: false }]
  no-unused-vars: ['error', {vars: 'all', varsIgnorePattern: '^_', args: 'all', argsIgnorePattern: '^_'}]
  eol-last: "warn"
  require-yield: off

overrides:
- files: [ 'src/javascripts/**/*.js' ]
  excludedFiles: [ '*.es6.js' ]
  globals:
    angular: false
    _: false
    JST: false
    $: false
- files: [ '*.es6.js' ]
  # Eslint configuration for files ending in .es6.js
  parserOptions:
    ecmaVersion: 2017
    sourceType: module
  rules:
    # ES6 specific
    prefer-const: error
    no-var: error

    # We disallow everything we do not transpile with babel
    no-restricted-syntax:
    - error
    - BreakStatement
    - ContinueStatement
    - DebuggerStatement
    - EmptyStatement
    - ForStatement
    - LabeledStatement
    - MetaProperty
    - SequenceExpression
    - TaggedTemplateExpression
    - UpdateExpression
    - WithStatement
