extends:
  - 'eslint:recommended'
  - './.eslint-standard.yml'
rules:
  # eslint:recommended overrides
  require-yield: off

  # eslint-standard overrides
  padded-blocks: off
  semi: ["error", "always"]

  # Other
  no-multiple-empty-lines: ["error", {max: 2, maxBOF: 0, maxEOF: 0}]
  no-unused-vars: ['error', {vars: 'all', args: 'all', argsIgnorePattern: '^_'}]
  eol-last: "error"
  generator-star-spacing: ['error', {before: false, after: true}]
  yield-star-spacing: ['error', {before: false, after: true}]
env:
  node: true
globals:
  angular: true
  _: true
  dotty: true
  JST: true
  $: true
