language: node_js
branches:
  only:
  - master
  - production
  - staging
node_js:
- '0.10'
before_install:
- npm config set always-auth true
- npm config set _auth Y2ZkOjBlOWNhYWYyYjExMTliYjdkZjY=
- npm config set registry https://contentful.registry.nodejitsu.com/
install:
- npm install -g jshint
- npm install -g slimerjs
- npm install
- bower install
before_script:
- npm install -g travis-notify-geckoboard
- gulp vendor-js templates user_interface
script:
- npm test
- npm run hint
after_script:
- |
  if [ $TRAVIS_BRANCH == 'master' ]; then
    travis-notify-geckoboard -a ed5192f6255498bc3fe120e1fd5f1983 -w 49147-989e9c70-495c-0131-abd5-22000a9e0b33
  fi
- bin/trigger-packagebot
notifications:
  slack:
    secure: lc+kwmitAcp5htZI5ETV5x5ZwP0TGzJKwenaMMyqGCCUlDgK76hBirkg9LgBhG5500Kks+udT6flZLJ0p/gNvbgqEaCR1GZBmCdneqxpkow8kAy2HUGR1MmkA3+zs1YMJ4Rp3nC78ygVKPzreqgEpmfCovYls0PmpO37khqzBnY=
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdXZjdVZnaW5NcURSQzQ1UElMTURuMGtGbU9NeThrNEttZXhBK0lPRWFPbzFlK1VSCnI5RkZJbEtEaWhhYnlHK0hyV0k2Z0o2VUZpeGJ4Nk1lUVNCcVA1d0FkcVBJMjE2SldnbElxSmIrWGpxTUNwY0cKNFNEcDlBNHI2UzJJUDZJdE9mSllrVVQ2M1J4Q0tSdFlNT3hYZ0tMNUk0SkJRV2YzeFFtVWIzcGR0ZjM5RU1yRQphbjY4ZlJEcW9kSlpCVllnRmtlNVkveStoNjRZdE9YT0U2ZVZRVGtUK2tGLzM3UElNRVBEWjdkQ25QRloxNGx3CnBEK0pVaWNxRzJCUDRJYyt1MGVEZVc3V1JsdlE3aTRCc0VJWEs1UW10bm1qN0RZSVVQQ2R6ZWY1RHJTRVpaVkMKVmZCZ2l5RThFR3R1NitjV2JtTUF6S3NydUljR0tFMStMNUtCNlFJREFRQUJBb0lCQVFDUTJMRVFQREgwZWp5YQpIRTFYUXZqNmJXTWx1RmNlKzdFZzRMVFJFMnNBc1Bwd210NGgvUm4zWmorOE9wbkVKZ3ZTR3JqQ0xwa0J1S24rCk4zUlg5bG42SDgwSUhRbWVVbFpNNThaZnZtTWc4M0ROUDRZMzRmeitkQUEyN1d5U0IvM0wxK0lmNFhZTTJUaTAKaWhmQUIwb2ZRYU9NaS93c1JQVGl0UEpIajJDTWZmK1U0bFQzNnRGM1lLaEdsbzVja3ZvTkxBenhqRDlHUng1UgpjNFdZM0N2UU51LzRGM1BUZ2dPUGlrdkIzQnRSNnVJNXRCclFkVmE5R3dmdi9qalA3OXliZFYzNHZxVWVhVDhBCnZRYkJjMERhNnBlMW9rYTZhSENxRUIralMxM3BRRzh3Vy9ZYlc2anlkaHFRRklrRjBmTHBFTUVib3NHVFdhQkQKNFBCZkNwclJBb0dCQU50aVY5azJmRnFqT2ZOV3kwWm9wdFl2MGR5WHVySlVyOVVKelM4TWwrSUdSYUUvR2RVawpPTFhHYkJlS2ozeTZTMHNFY1VUY1BncnFiVExzWjJaY0hDZWVla0U0b0ZIQkRLMDVNbTZpeE9ST3ZIOFloWDVlCk4vVXliYitJWHkvSWpTeFJoRTZmc0IzdTl1RmFmTWxRV2MyM1lpSGJ5bjRES1I0VkxmM05mSWt0QW9HQkFOb3IKcnd2RGNsVi9OcG10Rk1yWkQ4S1dBNVFzbWJ3ZVk3RTJ6cUQ5OTNXbm9qUm1ydkRFUVRXQ0pBMUdoNlJCTjJFUQpBQzd4NFJqOHRjZkxDd29SWkFEaXNvVEZ1TnpjdWZLN3pmRCtaemdHWGRERTRpanQ2L0s1L1Nvb1M2S2REOCtDCnJZNURwc1RCT3JOV3dndGVtVVByZDdZSyt5U284OGlONXFhd0RSa3RBb0dCQU1CUFIrVFAzMWh3cHpjSmlXMXkKQlhYU08ydmMwYnJMZzhzREtZc3B4ZVpMU3pSYkpTRHkvSWRUcGFOSlFoaTdFWTkwR0hxZGVnR0ZtQzNBajY5cAo1UUJSNnFkTHBUV2xQYUNIZUE4RnZnVEloSElCSTl3dmFXd1dSYUJWUWVPWU1UQjlVTGEvUXRvcWhOM3N2V0NYCmYvRlY1TDc3ZFZqYkdtc1ZjOWg5RGNNTkFvR0FQMVNPNjR0QWxURG9XSk8xaFd5YzlvODFXcjNYb3BQdnZIRjgKYVo5UFJnZnpQZUxReFhNeXVxV2NjWDRYd2Nac25QQllIVWg1WHhkOGJSS3prYWlhcnVjZml3c2FMb0trTjZIcwpsaGhEUGpBYTY0ODdWMFk1UjZ4Vm9QY3hmWEs2TkRKcXp2RTBaOGp2a1QrTjlGN3hmcFhMbWp4MXlwNkFwYWNMClhUZWRsY0VDZ1lCRDlmNFJ2QWVYbG8yRW5BWWpFN3hKVDA4ZFBubi8weS9saDJWZUVYb0NTcFMxTk5BZEwzRkIKOTdYY3hldEYwVTlicEl3aTM1dXNFcFZCR1l6K2QzVHNhdlBIQVVrNE5aTmFKVnhaQnJqWUV2NlY3dWdxSGkrYwoxSklINk03VFgyMWI0YTNTa3JyNzdvYitjdXBGNVpFTSt4WnM0cm5DR2tKd2VWcndpZTFtenc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
