sudo: required
dist: trusty
services:
  - docker

# Uses node version from .nvmrc
language: node_js

env:
  global:
    # Use by estivador
    - PACKAGE_BUCKET=pkg.contentful.org
    - DOCKER_REGISTRY=806120774687.dkr.ecr.us-east-1.amazonaws.com
    # Use in before_deploy and by estivador
    - DOCKER_IMAGE=contentful/user_interface
    # JENKINS_PASSWORD
    - secure: "RWpHqk1nc4k4qIJ6TgM8ofrwHL2nMkp5kg5B2jevJtW8UlSnzkVuagQN9Req9dTjaMX/ZsB1Pt4CQE5K1W/xQJTKAnbtyQ8fZOXU4kQvOH+TptdwK+oMwjfITktCYuj1c1/aMD0dzkIaPvjX/OwXZPtCRq2s762YXuCyPjx3ERU="
    # JENKINS_TOKEN
    - secure: "eXBRhtfrIBfoszICbvyBmIQxLf+JEp9+OeEh1FGbqWmKWXlDTApyt6+vsOEaD0Akrc4yYdIw+DdP43tFn9VbXzun1AL/RCjDqo6l9yNvCvA5k7rF2w9rAd+ZHKYRMGLvpQ4vfNEuWwiwtjdzLA9VvrDYU/484XuH/1pSpt0rOyw="

before_install:
# Install latest version of docker. We require at least 1.12
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce

install:
- bin/docker-build-ci

script:
- bin/docker-run-ci test

after_success:
# Build the package and static files
# TRAVIS_BRANCH:
#   - for push builds, or builds not triggered by a pull request, this is the name of the branch.
#   - for builds triggered by a pull request this is the name of the branch targeted by the pull request.
#   - for builds triggered by a tag, this is the same as the name of the tag (TRAVIS_TAG).
# TRAVIS_COMMIT: The commit that the current build is testing.
# TRAVIS_PULL_REQUEST: The pull request number if the current job is a pull request, “false” if it’s not a pull request.
#
# A pull request build (travis-ci/pr job) uses the merge commit of merging your PR branch HEAD with the HEAD of the branch
# the PR is opened against. This merge commit is made available transparently by GitHub. This is to check whether your PR
# when merged won't break things.
# Note that pull request builds skip the deployment step altogether. (travis-ci/pr job)
#
# A push build (travis-ci/push job) builds the latest commit pushed to your branch.
# travis-ci/push job is what does the deployment of assets.
#
# example params received by jobs for PR#2444
# travis-ci/pr -> master 178f0f7862a0f9b743e0af38479657fc3ef29aab 2444
# travis-ci/push -> refactor/task-runner 3de3452722bcd82ca484ecc16db550f175f2937e false
- bin/docker-run-ci travis --branch "${TRAVIS_BRANCH}" --version "${TRAVIS_COMMIT}" --pr "${TRAVIS_PULL_REQUEST}"

before_deploy:
- docker build -t $DOCKER_IMAGE -f Dockerfile-prod --build-arg CF_VERSION="${TRAVIS_COMMIT}" .

deploy:
  - provider: s3
    access_key_id: AKIAI35UEY5UVV5IT6BQ
    secret_access_key:
      secure: "Azx2DWNKfcFZhQoB1eR6dJ1F0QClJYLohozyzutOhpp86mUuoGXtBPOaiD0kfM8sNFdlhyjagVZo30wMCXBw5t9qSDqEpCOOhZk4kRNnInCh+ha/H14FFbxki7TaWn9RQXmTIoGh5JSmIZ5RDYRJZRyoL4Da11CojildoBD7wJ8="
    bucket: cf-preview-static-cdnorigin
    region: eu-west-1
    local-dir: output/files/preview
    acl: public_read
    skip_cleanup: true
    on:
      all_branches: true
  ## Deploy all branches to staging preview
  - provider: s3
    access_key_id: AKIAJHQB2MH23CVUXK6Q
    secret_access_key:
      secure: "DPVDc2YHfDuquRY2JxGkaNYq4j3xuhr0e+MFUIvo61zxLpXeueBLKgmG6n/bnRFGiN2vFOUi3K404/adVOH4OuQedsjOx9Ew/ubUSM582DEhmFzqSicDOJm9kTA3+9u4OA2UiKw4pdYZ+/jTqjwMzr1GLaV5RAnlH2jue/XLhcc="
    bucket: static.cdnorigin.flinkly.com
    region: us-east-1
    local-dir: output/files/staging
    acl: public_read
    skip_cleanup: true
    on:
      all_branches: true
  ## Deploy production assets only when the branch that was pushed to is 'production'
  - provider: s3
    access_key_id: AKIAITC7MCJO3VAWCEOA
    secret_access_key:
      secure: "G2e17qRtyDKnRhFxvucKt0AP3jPsydabJ4s0LJHTfaWd+D8YPompFU8SussNrOaUQmPi5OlBKA4fTp2XQOI4l/bLy/5Q6Z11Ihze8BVeFICgHg0pYvLrJG+id2HAn8aG0W0HbQi0x/V/7m7i+j2MeIg6taO6PodJ4j+8vNoWwwg="
    bucket: static.cdnorigin.contentful.com
    region: us-east-1
    local-dir: output/files/production
    acl: public_read
    skip_cleanup: true
    on: 'production'
  # Deploy production preview assets.
  # This is the same as the one above but with a different branch name
  - provider: s3
    access_key_id: AKIAITC7MCJO3VAWCEOA
    secret_access_key:
      secure: "G2e17qRtyDKnRhFxvucKt0AP3jPsydabJ4s0LJHTfaWd+D8YPompFU8SussNrOaUQmPi5OlBKA4fTp2XQOI4l/bLy/5Q6Z11Ihze8BVeFICgHg0pYvLrJG+id2HAn8aG0W0HbQi0x/V/7m7i+j2MeIg6taO6PodJ4j+8vNoWwwg="
    bucket: static.cdnorigin.contentful.com
    region: us-east-1
    local-dir: output/files/production
    acl: public_read
    skip_cleanup: true
    on: 'production-preview/*'
  # Deploys package and image. This requires the assets to be available
  # already
  - provider: script
    script: ./tools/push-and-promote.sh
    skip_cleanup: true
    on:
      all_branches: true
after_script:
  - bin/travis-run-jenkins

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      - secure: lc+kwmitAcp5htZI5ETV5x5ZwP0TGzJKwenaMMyqGCCUlDgK76hBirkg9LgBhG5500Kks+udT6flZLJ0p/gNvbgqEaCR1GZBmCdneqxpkow8kAy2HUGR1MmkA3+zs1YMJ4Rp3nC78ygVKPzreqgEpmfCovYls0PmpO37khqzBnY=

source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdXZjdVZnaW5NcURSQzQ1UElMTURuMGtGbU9NeThrNEttZXhBK0lPRWFPbzFlK1VSCnI5RkZJbEtEaWhhYnlHK0hyV0k2Z0o2VUZpeGJ4Nk1lUVNCcVA1d0FkcVBJMjE2SldnbElxSmIrWGpxTUNwY0cKNFNEcDlBNHI2UzJJUDZJdE9mSllrVVQ2M1J4Q0tSdFlNT3hYZ0tMNUk0SkJRV2YzeFFtVWIzcGR0ZjM5RU1yRQphbjY4ZlJEcW9kSlpCVllnRmtlNVkveStoNjRZdE9YT0U2ZVZRVGtUK2tGLzM3UElNRVBEWjdkQ25QRloxNGx3CnBEK0pVaWNxRzJCUDRJYyt1MGVEZVc3V1JsdlE3aTRCc0VJWEs1UW10bm1qN0RZSVVQQ2R6ZWY1RHJTRVpaVkMKVmZCZ2l5RThFR3R1NitjV2JtTUF6S3NydUljR0tFMStMNUtCNlFJREFRQUJBb0lCQVFDUTJMRVFQREgwZWp5YQpIRTFYUXZqNmJXTWx1RmNlKzdFZzRMVFJFMnNBc1Bwd210NGgvUm4zWmorOE9wbkVKZ3ZTR3JqQ0xwa0J1S24rCk4zUlg5bG42SDgwSUhRbWVVbFpNNThaZnZtTWc4M0ROUDRZMzRmeitkQUEyN1d5U0IvM0wxK0lmNFhZTTJUaTAKaWhmQUIwb2ZRYU9NaS93c1JQVGl0UEpIajJDTWZmK1U0bFQzNnRGM1lLaEdsbzVja3ZvTkxBenhqRDlHUng1UgpjNFdZM0N2UU51LzRGM1BUZ2dPUGlrdkIzQnRSNnVJNXRCclFkVmE5R3dmdi9qalA3OXliZFYzNHZxVWVhVDhBCnZRYkJjMERhNnBlMW9rYTZhSENxRUIralMxM3BRRzh3Vy9ZYlc2anlkaHFRRklrRjBmTHBFTUVib3NHVFdhQkQKNFBCZkNwclJBb0dCQU50aVY5azJmRnFqT2ZOV3kwWm9wdFl2MGR5WHVySlVyOVVKelM4TWwrSUdSYUUvR2RVawpPTFhHYkJlS2ozeTZTMHNFY1VUY1BncnFiVExzWjJaY0hDZWVla0U0b0ZIQkRLMDVNbTZpeE9ST3ZIOFloWDVlCk4vVXliYitJWHkvSWpTeFJoRTZmc0IzdTl1RmFmTWxRV2MyM1lpSGJ5bjRES1I0VkxmM05mSWt0QW9HQkFOb3IKcnd2RGNsVi9OcG10Rk1yWkQ4S1dBNVFzbWJ3ZVk3RTJ6cUQ5OTNXbm9qUm1ydkRFUVRXQ0pBMUdoNlJCTjJFUQpBQzd4NFJqOHRjZkxDd29SWkFEaXNvVEZ1TnpjdWZLN3pmRCtaemdHWGRERTRpanQ2L0s1L1Nvb1M2S2REOCtDCnJZNURwc1RCT3JOV3dndGVtVVByZDdZSyt5U284OGlONXFhd0RSa3RBb0dCQU1CUFIrVFAzMWh3cHpjSmlXMXkKQlhYU08ydmMwYnJMZzhzREtZc3B4ZVpMU3pSYkpTRHkvSWRUcGFOSlFoaTdFWTkwR0hxZGVnR0ZtQzNBajY5cAo1UUJSNnFkTHBUV2xQYUNIZUE4RnZnVEloSElCSTl3dmFXd1dSYUJWUWVPWU1UQjlVTGEvUXRvcWhOM3N2V0NYCmYvRlY1TDc3ZFZqYkdtc1ZjOWg5RGNNTkFvR0FQMVNPNjR0QWxURG9XSk8xaFd5YzlvODFXcjNYb3BQdnZIRjgKYVo5UFJnZnpQZUxReFhNeXVxV2NjWDRYd2Nac25QQllIVWg1WHhkOGJSS3prYWlhcnVjZml3c2FMb0trTjZIcwpsaGhEUGpBYTY0ODdWMFk1UjZ4Vm9QY3hmWEs2TkRKcXp2RTBaOGp2a1QrTjlGN3hmcFhMbWp4MXlwNkFwYWNMClhUZWRsY0VDZ1lCRDlmNFJ2QWVYbG8yRW5BWWpFN3hKVDA4ZFBubi8weS9saDJWZUVYb0NTcFMxTk5BZEwzRkIKOTdYY3hldEYwVTlicEl3aTM1dXNFcFZCR1l6K2QzVHNhdlBIQVVrNE5aTmFKVnhaQnJqWUV2NlY3dWdxSGkrYwoxSklINk03VFgyMWI0YTNTa3JyNzdvYitjdXBGNVpFTSt4WnM0cm5DR2tKd2VWcndpZTFtenc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
