# Builds an image to run test on CI.
#
# This image includes all dependencies, dev dependencies and the source
# code. It also includes a built version of the application.
#
# The image exposes an entry command that runs specific tasks like
# running the tests or creating a distribution. For details see
# `tools/docker/entry-script.js`.
#
# To build this image use `bin/docker-build-ci` and to run this image
# use `bin/docker-run-ci`.
#
# Build arguments:
# * NPM_TOKEN used to fetch private NPM package from the @contentful
#   scope. Required.
# * SSH_KEY plain SSH key to fetch NPM dependencies from Github.
#   Optional.

# The base image is hosted on Docker hub and built using
# `tools/docker/base/Dockerfile`.
FROM contentful/user-interface-base:7
WORKDIR /app

ENV PATH=/app/node_modules/.bin:$PATH \
    NPM_CONFIG_LOGLEVEL=warn \
    # Used by karma launcher
    CHROME_BIN=/usr/bin/google-chrome

ARG NPM_TOKEN
RUN \
  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc && \
  mkdir ~/.ssh

# Install dependencies
COPY package.json package-lock.json ./

ARG SSH_KEY
RUN \
  ssh-keyscan github.com > ~/.ssh/known_hosts && \
  echo "$SSH_KEY" > ~/.ssh/id_rsa && \
  chmod 0600 ~/.ssh/id_rsa && \
  npm install --no-optional --unsafe-perm && \
  rm -f ~/.ssh/id_rsa

# Copy source files and build app
COPY ./ ./
ARG NODE_ENV
RUN NODE_ENV=${NODE_ENV} node --max_old_space_size=8096 ./node_modules/.bin/gulp build

ENTRYPOINT ["bin/docker-entry"]
