#!/bin/bash

set -ev

./bin/provision

SLIMERJS_BIN=bin/slimerjs

./bin/install-firefox
./bin/install_slimerjs
npm install --no-optional

git submodule update --init

pushd vendor/ui-extensions-sdk
  npm install --production --no-optional
  make
popd
