#!/bin/bash

set -ev

./bin/provision

SLIMERJS_BIN=bin/slimerjs

./bin/install_slimerjs
npm install --no-optional
./node_modules/bower/bin/bower install

git submodule update --init

pushd vendor/contentful-widget-sdk
  npm install --production --no-optional
  make
popd
