#!/bin/bash

set -x
set -e
umask 0022

package_name="cf-user-interface"
version="0.$(date '+%s')-g$(git log -1 --pretty=format:%h)"
# strip first character from version
#version=${version:1}

if [ -z "$BUILD_ROOT" ]; then
  BUILD_ROOT=$(mktemp -d -t user-interface.XXXX.$version);
  echo "Warning: BUILD_ROOT was not set. building package in $BUILD_ROOT"
fi

# We will regret this!
#node_version=$(jq -r '.dist?.nodeVersion? // "v0.10.31"' package.json)
node_version="v0.10.33"
node_tarball="node-${node_version}-linux-x64.tar.gz"
#node_checksum=$(grep $node_tarball $node_checksum_file)
node_checksum="4eba69caf7368d7f388700eb02996f85b06f457a  node-v0.10.33-linux-x64.tar.gz"


PACKAGE_ROOT=$BUILD_ROOT/opt/contentful/$package_name
mkdir -p $PACKAGE_ROOT

wget -nv http://nodejs.org/dist/${node_version}/${node_tarball}
sha1sum --strict -c <(echo "$node_checksum")
tar xz --strip-components=1 -f $node_tarball
rm $node_tarball
export PATH="$(pwd)/bin:$PATH"
npm install -g --prefix $(pwd) npm@~2.4.8
npm install --production
node_modules/bower/bin/bower install

node_modules/.bin/gulp package

pushd $PACKAGE_ROOT
  mkdir build bin
popd

rsync -avz build/. $PACKAGE_ROOT/build/.
cp -p bin/process_hosts $PACKAGE_ROOT/bin

fpm -t deb -s dir \
  -n $package_name \
  --version $version \
  --exclude '**/.nfs*' \
  -C $BUILD_ROOT \
  opt
