# Eslint configuration for files ending in .es6.js
globals:
  window: false
  setTimeout: false
  clearTimeout: false
  Promise: false
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  # ES6 specific
  prefer-const: error
  no-var: error
  # We disallow everything we do not transpile with babel
  no-restricted-syntax:
  - error
  - BreakStatement
  - ClassBody
  - ClassDeclaration
  - ClassExpression
  - ContinueStatement
  - DebuggerStatement
  - EmptyStatement
  - ExperimentalRestProperty
  - ExperimentalSpreadProperty
  - ForStatement
  - ForInStatement
  - ForOfStatement
  - LabeledStatement
  - MetaProperty
  - MethodDefinition
  - SequenceExpression
  - Super
  - SwitchCase
  - SwitchStatement
  - TaggedTemplateExpression
  - UpdateExpression
  - WithStatement
  - JSXIdentifier
  - JSXNamespacedName
  - JSXMemberExpression
  - JSXEmptyExpression
  - JSXExpressionContainer
  - JSXElement
  - JSXClosingElement
  - JSXOpeningElement
  - JSXAttribute
  - JSXSpreadAttribute
  - JSXText
