version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1

jobs:
  all-the-things:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: bin/docker-build-ci
      - run: bin/docker-run-ci test
      - run: bin/docker-run-ci travis --branch "${CIRCLE_BRANCH}" --version "${CIRCLE_SHA1}" --pr "false"
      - persist_to_workspace:
          root: .
          paths:
            - output

  deploy-to-preview:
    machine:
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: /workspace
      - run: docker build -t aws -f Dockerfile-awscli .
      - run:
          name: Deploy to preview
          command: |
            docker run -t --rm -v /workspace/output:/app/output \
            -e AWS_REGION=eu-west-1 \
            -e AWS_ACCESS_KEY_ID=${AWS_S3_PREVIEW_ACCESS_KEY_ID} \
            -e AWS_SECRET_ACCESS_KEY=${AWS_S3_PREVIEW_SECRET_ACCESS_KEY} \
            aws s3 cp --acl public-read --recursive \
            /app/output/files/preview s3://cf-preview-static-cdnorigin

  deploy-to-staging:
    machine:
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: /workspace
      - run: docker build -t aws -f Dockerfile-awscli .
      - run:
          name: Deploy to staging
          command: |
            docker run -t --rm -v /workspace/output:/app/output \
            -e AWS_REGION=us-east-1 \
            -e AWS_ACCESS_KEY_ID=${AWS_S3_STAGING_ACCESS_KEY_ID} \
            -e AWS_SECRET_ACCESS_KEY=${AWS_S3_STAGING_SECRET_ACCESS_KEY} \
            aws s3 cp --acl public-read --recursive \
            /app/output/files/staging s3://cf-staging-static-cdnorigin

  deploy-to-production:
    machine:
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: /workspace
      - run: docker build -t aws -f Dockerfile-awscli .
      - run:
          name: Deploy to production
          command: |
            docker run -t --rm -v /workspace/output:/app/output \
            -e AWS_REGION=us-east-1 \
            -e AWS_ACCESS_KEY_ID=${AWS_S3_PRODUCTION_ACCESS_KEY_ID} \
            -e AWS_SECRET_ACCESS_KEY=${AWS_S3_PRODUCTION_SECRET_ACCESS_KEY} \
            aws s3 cp --acl public-read --recursive \
            /app/output/files/production s3://static.cdnorigin.contentful.com

  push-image-to-docker-repo:
    machine:
      docker_layer_caching: true
    environment:
      DOCKER_REGISTRY: 806120774687.dkr.ecr.us-east-1.amazonaws.com
      DOCKER_IMAGE: contentful/user_interface
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - run: cp /workspace/output .
      - run: docker build -t $DOCKER_IMAGE -f Dockerfile-prod --build-arg CF_VERSION="${CIRCLE_SHA1}" .
      - run:
          name: Push image to our docker repo
          command: |
            curl -fsSLO https://contentful-lab-assets.s3.amazonaws.com/estivador && chmod +x estivador
            echo "$(curl -sSL https://contentful-lab-assets.s3.amazonaws.com/estivador.sum)" | sha512sum -c
            ./estivador docker-ecr-login
            ./estivador put-image
            ./estivador notify-slack

  deploy-microbackend:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Deploy microbackend
          command: |
            cd micro-backends
            docker build -t microbackend --build-arg NPM_TOKEN .
            docker run -t --rm $(pwd):/app \
            -e AWS_REGION=${MICRO_BACKENDS_AWS_REGION} \
            -e AWS_ACCESS_KEY_ID=${MICRO_BACKENDS_AWS_ACCESS_KEY_ID} \
            -e AWS_SECRET_ACCESS_KEY=${MICRO_BACKENDS_AWS_SECRET_ACCESS_KEY} \
            -e CIRCLE_SHA1 \
            -w /app/.scripts \
            microbackend \
            node deploy.js "rev-$CIRLE_SHA1"

  trigger-jenkins:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: bin/travis-run-jenkins


workflows:
  build:
    jobs:
      - all-the-things
      - cypress/run:
          executor: cypress/base-8
          pre-steps:
            - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
          store_artifacts: true

notify:
  webhooks:
    - url: https://samson.contentful.org/integrations/circleci/24884e787b5439c88cedef3d8bf1ca90
