version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
  deploy-assets:
    orbs:
      aws-s3: circleci/aws-s3@1.0.4
    jobs:
      to-s3:
        description: 'Build the image containing awscli and deploy assets to S3 using it'
        parameters:
          access_key_id:
            type: string
          secret_access_key:
            type: string
          region:
            type: string
          path:
            type: string
          bucket:
            type: string
        docker:
          - image: circleci/python:2.7
        steps:
          - attach_workspace:
              at: ~/workspace
          - checkout
          - run:
              name: Export AWS environment variables
              command: |
                echo 'export AWS_ACCESS_KEY_ID=<<parameters.access_key_id>>' >> $BASH_ENV
                echo 'export AWS_SECRET_ACCESS_KEY=<<parameters.secret_access_key>>' >> $BASH_ENV
                echo 'export AWS_REGION=<<parameters.region>>' >> $BASH_ENV
          - aws-s3/copy:
              from: <<parameters.path>>
              to: s3://<<parameters.bucket>>
              arguments: '--acl public-read --recursive'

executors:
  cypress-base-8:
    docker:
      - image: 'cypress/base:8'
    environment:
      NODE_ENV: dev
      UI_CONFIG: localhost

jobs:
  build-and-push-image:
    machine:
      docker_layer_caching: true
    environment:
      DOCKER_IMAGE: contentful/user_interface
      DOCKER_REGISTRY: 806120774687.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Setup environment variables
          command: |
            echo 'export SSH_KEY="$(openssl rsa -in ~/.ssh/id_rsa)"' >> $BASH_ENV
      - run:
          name: Build production image
          command: |
            docker-compose build production
      - run:
          name: Build assets image
          command: |
            # create a container from the "built" target
            # this is so that we can copy the output folder from it
            # This is extremely fast as all layers used by it are already
            # cached by building the production image earlier
            docker-compose up --no-start --build generate-assets
            docker cp user_interface-built-assets:app/output .
      - run:
          name: Push production image to our docker repo
          command: |
            curl -fsSLO https://contentful-lab-assets.s3.amazonaws.com/estivador && chmod +x estivador
            echo "$(curl -sSL https://contentful-lab-assets.s3.amazonaws.com/estivador.sum)" | sha512sum -c
            ./estivador docker-ecr-login
            ./estivador put-image
      - run:
          name: Trigger jenkins E2E tests
          command: bin/trigger-jenkins
      - persist_to_workspace:
          root: .
          paths:
            - output

  deploy-micro-backends:
    docker:
      - image: circleci/node:8.10
    environment:
      LOG: 'yesplease'
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo $'export MICRO_BACKENDS_VERSION="$(cat package-lock.json | jq \'.dependencies["@contentful/micro-backends"].version\' --raw-output)"' >> $BASH_ENV
            echo 'export AWS_REGION="$MICRO_BACKENDS_AWS_REGION"' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID="$MICRO_BACKENDS_AWS_ACCESS_KEY_ID"' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY="$MICRO_BACKENDS_AWS_SECRET_ACCESS_KEY"' >> $BASH_ENV
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Deploy micro-backends
          command: |
            echo "Using @contentful/micro-backends@$MICRO_BACKENDS_VERSION"
            npx "@contentful/micro-backends@$MICRO_BACKENDS_VERSION" "micro-backends" "rev-$CIRCLE_SHA1"

  lint:
    docker:
      - image: circleci/node:10.15.3
    environment:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: echo 'export SSH_KEY="$(openssl rsa -in ~/.ssh/id_rsa)"' >> $BASH_ENV
      - run: npm ci
      - run: tools/bin/validate-config.js config/*.json
      - run: npm run hint

  run-jest-tests:
    docker:
      - image: circleci/node:10.15.3
    environment:
      CI: true
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: echo 'export SSH_KEY="$(openssl rsa -in ~/.ssh/id_rsa)"' >> $BASH_ENV
      - run: npm ci
      - run:
          name: Run Jest tests
          command: NODE_ENV=production npm run jest:coverage # cant set NODE_ENV in environment above since jest is a dev dep
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/jest-test-results.xml'
      - run: npm run codecov
      - store_test_results:
          path: reports/junit

  run-karma-tests:
    docker:
      - image: circleci/node:10.15.3-browsers
    environment:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: echo 'export SSH_KEY="$(openssl rsa -in ~/.ssh/id_rsa)"' >> $BASH_ENV
      - run: npm ci
      - run:
          name: Build test artifacts
          command: NODE_ENV=production node --max_old_space_size=3072 ./node_modules/.bin/gulp build-test
      - run:
          name: Run Karma tests
          command: |
            mkdir -p ./reports/junit
            NODE_ENV=production npm run test:once
          environment:
            JUNIT_REPORT_PATH: ./reports/junit
            JUNIT_REPORT_NAME: karma-test-results.xml
      - store_test_results:
          path: reports/junit

workflows:
  build:
    jobs:
      - build-and-push-image
      - lint
      - run-jest-tests
      - run-karma-tests
      - deploy-micro-backends
      - cypress/run:
          name: cypress-run
          executor: cypress-base-8
          pre-steps:
            - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
          start: npm start
          wait-on: 'http://localhost:3001'
          store_artifacts: true
      - deploy-assets/to-s3:
          name: deploy-assets-to-preview
          access_key_id: '${AWS_S3_PREVIEW_ACCESS_KEY_ID}'
          secret_access_key: '${AWS_S3_PREVIEW_SECRET_ACCESS_KEY}'
          region: 'eu-west-1'
          path: '~/workspace/output/files/preview'
          bucket: 'cf-preview-static-cdnorigin'
          requires:
            - build-and-push-image
      - deploy-assets/to-s3:
          name: deploy-assets-to-staging
          access_key_id: '${AWS_S3_STAGING_ACCESS_KEY_ID}'
          secret_access_key: '${AWS_S3_STAGING_SECRET_ACCESS_KEY}'
          region: 'us-east-1'
          path: '~/workspace/output/files/staging'
          bucket: 'cf-staging-static-cdnorigin'
          post-steps:
            - run:
                name: Trigger Jenkins Staging Dependent Tests
                command: bin/trigger-jenkins-dependent
          requires:
            - build-and-push-image
      - deploy-assets/to-s3:
          name: deploy-assets-to-prod
          access_key_id: '${AWS_S3_PRODUCTION_ACCESS_KEY_ID}'
          secret_access_key: '${AWS_S3_PRODUCTION_SECRET_ACCESS_KEY}'
          region: 'us-east-1'
          path: '~/workspace/output/files/production'
          bucket: 'static.cdnorigin.contentful.com'
          requires:
            - build-and-push-image

notify:
  webhooks:
    - url: https://samson.contentful.org/integrations/circleci/24884e787b5439c88cedef3d8bf1ca90
