export const fixtures = {
  role: {
    name: 'Editor with tags',
    description: 'Allows editing, publishing and archiving of content -  tag-based rules',
    policies: [
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Entry'] }] },
        actions: ['update'],
      },
      {
        effect: 'allow',
        constraint: {
          and: [
            { equals: [{ doc: 'sys.type' }, 'Entry'] },
            { equals: [{ doc: 'sys.createdBy.sys.id' }, 'User.current()'] },
          ],
        },
        actions: ['update'],
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Entry'] }] },
        actions: ['delete'],
      },
      {
        effect: 'allow',
        constraint: {
          and: [
            { equals: [{ doc: 'sys.type' }, 'Entry'] },
            { equals: [{ doc: 'sys.id' }, '2JA7S5tIHhz2XqKEEsOkrw'] },
            { equals: [{ doc: 'sys.contentType.sys.id' }, 'author'] },
          ],
        },
        actions: 'all',
      },
      {
        effect: 'allow',
        constraint: {
          and: [
            { equals: [{ doc: 'sys.type' }, 'Entry'] },
            { equals: [{ doc: 'sys.contentType.sys.id' }, 'category'] },
          ],
        },
        actions: ['archive', 'unarchive'],
      },
      {
        effect: 'deny',
        constraint: {
          and: [
            { equals: [{ doc: 'sys.type' }, 'Entry'] },
            { equals: [{ doc: 'sys.createdBy.sys.id' }, 'User.current()'] },
            { equals: [{ doc: 'sys.contentType.sys.id' }, 'photoGallery'] },
          ],
        },
        actions: ['read'],
      },
      {
        effect: 'deny',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Entry'] }] },
        actions: ['create'],
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: ['read'],
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: 'all',
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: 'all',
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: ['update'],
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: 'all',
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: ['archive', 'unarchive'],
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: 'all',
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: 'all',
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: ['create'],
      },
      {
        effect: 'allow',
        constraint: {
          and: [
            { equals: [{ doc: 'sys.type' }, 'Asset'] },
            { equals: [{ doc: 'sys.id' }, 'BsLDVhZSsxbbcgVwBa6lK'] },
          ],
        },
        actions: ['update'],
      },
      {
        effect: 'allow',
        constraint: { and: [{ equals: [{ doc: 'sys.type' }, 'Asset'] }] },
        actions: ['delete'],
      },
      {
        effect: 'deny',
        constraint: {
          and: [
            { equals: [{ doc: 'sys.type' }, 'Asset'] },
            { equals: [{ doc: 'sys.id' }, '2x32KnbRR5pBLXcAHETvQv'] },
          ],
        },
        actions: ['delete'],
      },
    ],
    permissions: {
      contentModel: { read: true, manage: false },
      contentDelivery: { read: false, manage: false },
      settings: { manage: false },
      environments: { manage: false },
      environmentAliases: { manage: false },
      tags: { manage: false },
    },
    sys: {
      type: 'Role',
      id: '6j9gQ8bldzhaeFuVEnemaC',
      version: 91,
      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
      createdBy: { sys: { type: 'Link', linkType: 'User', id: '4h9fOXzCd4aKn4aByEC5Uk' } },
      createdAt: '2020-09-16T16:51:37Z',
      updatedBy: { sys: { type: 'Link', linkType: 'User', id: '0DxkEpRWNGmuSrDf704wJM' } },
      updatedAt: '2020-12-01T16:14:02Z',
    },
  },
  entities: {
    Entry: {
      '2JA7S5tIHhz2XqKEEsOkrw': {
        entity: {
          persistenceContext: {
            _baseRequest: {
              adapter: {},
              _params: { path: '/spaces/m8xyo6sh8zj8/entries', headers: {}, putHeaders: {} },
            },
            identityMap: {
              _entities: {
                'Space.m8xyo6sh8zj8': {
                  persistenceContext: {
                    _baseRequest: { _params: { path: '/spaces', headers: {}, putHeaders: {} } },
                  },
                  data: {
                    name: 'Tags',
                    activatedAt: '2020-05-05T12:50:34Z',
                    sys: {
                      type: 'Space',
                      id: 'm8xyo6sh8zj8',
                      version: 12,
                      createdBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4h9fOXzCd4aKn4aByEC5Uk' },
                      },
                      createdAt: '2019-10-02T12:44:54Z',
                      updatedBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4ipGsNB8KSJDAbXgcekeHk' },
                      },
                      updatedAt: '2020-03-31T09:21:26Z',
                      organization: {
                        name: 'Developer Workflows Test Org',
                        subscriptionState: null,
                        isBillable: true,
                        trialPeriodEndsAt: null,
                        cancellationActiveAt: null,
                        hasSsoEnabled: false,
                        sys: {
                          type: 'Organization',
                          id: '4haCJX5hLV4DKJhIJz4A6k',
                          version: 5,
                          createdBy: {
                            sys: { type: 'Link', linkType: 'User', id: '4h9fOXzCd4aKn4aByEC5Uk' },
                          },
                          createdAt: '2019-04-29T13:20:57Z',
                          updatedAt: '2019-07-24T07:52:07Z',
                        },
                        disableAnalytics: false,
                      },
                    },
                    currentShard: {
                      state: 'online',
                      shardId: 8,
                      pid: 'zdr',
                      sys: {
                        type: 'Shard',
                        id: '400173',
                        version: 17,
                        createdAt: '2019-11-21T06:05:27Z',
                        updatedAt: '2020-01-17T12:41:37Z',
                      },
                    },
                    spaceMembership: {
                      admin: true,
                      sys: {
                        type: 'SpaceMembership',
                        id: '1zfXldeGQ2qWjMylMZSj0K',
                        version: 1,
                        user: {
                          firstName: 'Vincenzo',
                          lastName: 'Bianco',
                          avatarUrl:
                            'https://lh3.googleusercontent.com/a-/AOh14GjlZZP8GCEHBxlRgv1wHWUn7LXEPvH_PBBG_Cth=s96-c',
                          email: 'vincenzo.bianco@contentful.com',
                          cookieConsentData:
                            '{"userInterface":{"rawConsentRecord":"3cs9V63o8MMq6EkdWoh8veHPdp2XuEyD15QoU6PGhbDKA3qKfIqiZcwkXLtn3hiofGUf-wTE_UBTL0zO852zOEUWx553Fxj7MKYrQet6ilxcMDD9LAt8uQf3F25I4J5n4fbeX0ZG4bKa57OqWlCmJBHLqliq-x-T1D3ceXHCgmgts_iaSpbVrQENxCZKw5Au_yOdbHCuP5miLaJdYSnaoLleEuungDxgDl27G5KWb8iTRDAEewSDosqe5iWJTP8eZ8TWFCyH4uyulW5s-qgfG2xVSIXipxi2Ci-_5drXMmWbTvmnUtNP71VNPMWLImaxofoOciN8WqW0izmcogIOxZrPElEOtoD0inFQKItjtK_ctXcxcY8zflVf37e0POx9x0r41UeGcCvLuJG3rDrsnt179yJ-hJ7VMXXqxPp82Tba1BbbD9Itj3_braxSsDtg88_MyziJyMY=","expirationDate":1638718887540,"uuid":"48a83137-2d28-4844-90e5-149861e7fcd7","consentRecord":{"ESSENTIAL":"ACCEPT","STORAGE":"ACCEPT","MARKETING":"ACCEPT","PERSONALIZATION":"ACCEPT","ANALYTICS":"ACCEPT","OPT_OUT":"DENY"}}}',
                          activated: true,
                          signInCount: 8,
                          confirmed: true,
                          '2faEnabled': false,
                          intercomUserSignature:
                            'a5e97a5d564117ee8473e9cda8def026926ef31d023ae6a27e4d7e096270b518',
                          canCreateOrganization: true,
                          features: { logAnalytics: true, showPreview: false },
                          sys: {
                            type: 'User',
                            id: '0DxkEpRWNGmuSrDf704wJM',
                            version: 12,
                            createdAt: '2020-11-16T15:41:13Z',
                            updatedAt: '2020-11-26T08:42:11Z',
                          },
                          organizationMemberships: [
                            {
                              role: 'owner',
                              sys: {
                                type: 'OrganizationMembership',
                                id: '0DGwZZ2qnG6ZfPtQW0vs4C',
                                version: 0,
                                createdAt: '2020-11-16T15:41:13Z',
                                updatedAt: '2020-11-16T15:41:13Z',
                                status: 'active',
                                lastActiveAt: '2020-12-01T16:31:38Z',
                                sso: null,
                              },
                              organization: {
                                name: 'Contentful',
                                subscriptionState: null,
                                isBillable: false,
                                trialPeriodEndsAt: null,
                                cancellationActiveAt: null,
                                hasSsoEnabled: false,
                                sys: {
                                  type: 'Organization',
                                  id: '0DzC3fPm0Ll1kCsGmiUBJY',
                                  version: 0,
                                  createdAt: '2020-11-16T15:41:13Z',
                                  updatedAt: '2020-11-16T15:41:13Z',
                                },
                                disableAnalytics: false,
                              },
                            },
                            {
                              role: 'developer',
                              sys: {
                                type: 'OrganizationMembership',
                                id: '1xmKAGbI3JXPFXvNNTmKbo',
                                version: 1,
                                createdBy: {
                                  sys: {
                                    type: 'Link',
                                    linkType: 'User',
                                    id: '0Wqpu0iURWIzkfkG7a4pKb',
                                  },
                                },
                                createdAt: '2020-11-17T08:38:31Z',
                                updatedBy: {
                                  sys: {
                                    type: 'Link',
                                    linkType: 'User',
                                    id: '0Wqpu0iURWIzkfkG7a4pKb',
                                  },
                                },
                                updatedAt: '2020-11-17T08:40:17Z',
                                status: 'active',
                                lastActiveAt: '2020-12-01T16:31:38Z',
                                sso: null,
                              },
                            },
                          ],
                        },
                        createdBy: {
                          sys: { type: 'Link', linkType: 'User', id: '0Wqpu0iURWIzkfkG7a4pKb' },
                        },
                        createdAt: '2020-11-17T08:38:33Z',
                        updatedBy: {
                          sys: { type: 'Link', linkType: 'User', id: '0Wqpu0iURWIzkfkG7a4pKb' },
                        },
                        updatedAt: '2020-11-17T08:38:33Z',
                      },
                      roles: [],
                    },
                    spaceMember: {
                      admin: true,
                      sys: {
                        type: 'SpaceMember',
                        id: 'm8xyo6sh8zj8-0DxkEpRWNGmuSrDf704wJM',
                        createdAt: '2020-03-31T09:17:52Z',
                        updatedAt: '2020-11-26T08:42:11Z',
                        relatedMemberships: [
                          {
                            sys: {
                              type: 'Link',
                              linkType: 'TeamSpaceMembership',
                              id: '3hUKoy8aJrvHznOTV45Xfx',
                            },
                          },
                          null,
                        ],
                      },
                      roles: [],
                    },
                    shards: [null],
                  },
                  environment: {
                    name: 'lot-of-tags',
                    sys: {
                      type: 'Environment',
                      id: 'lot-of-tags',
                      version: 3,
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      status: { sys: { type: 'Link', linkType: 'Status', id: 'ready' } },
                      createdBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4ipGsNB8KSJDAbXgcekeHk' },
                      },
                      createdAt: '2020-11-27T08:31:28Z',
                      updatedBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4ipGsNB8KSJDAbXgcekeHk' },
                      },
                      updatedAt: '2020-11-27T08:31:29Z',
                      aliases: [
                        { sys: { type: 'Link', linkType: 'EnvironmentAlias', id: 'master' } },
                      ],
                    },
                  },
                  environmentMeta: {
                    environmentId: 'lot-of-tags',
                    isMasterEnvironment: true,
                    optedIn: true,
                    aliasId: 'master',
                  },
                },
                'ContentType.published.author': {
                  persistenceContext: {
                    _baseRequest: {
                      _params: {
                        path: '/spaces/m8xyo6sh8zj8/content_types',
                        headers: {},
                        putHeaders: {},
                      },
                    },
                  },
                  _publishedVersion: true,
                  data: {
                    name: 'Author',
                    fields: [
                      {
                        id: 'name',
                        apiName: 'name',
                        name: 'Name',
                        type: 'Symbol',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'twitterHandle',
                        apiName: 'twitterHandle',
                        name: 'Twitter handle',
                        type: 'Symbol',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'profilePhoto',
                        apiName: 'profilePhoto',
                        name: 'Profile photo',
                        type: 'Link',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        linkType: 'Asset',
                      },
                      {
                        id: 'biography',
                        apiName: 'biography',
                        name: 'Biography',
                        type: 'Text',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'createdEntries',
                        apiName: 'createdEntries',
                        name: 'Created entries',
                        type: 'Array',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        items: {
                          type: 'Link',
                          validations: [{ linkContentType: ['image'] }],
                          linkType: 'Entry',
                        },
                      },
                      {
                        id: 'DlBLCNlzGFA0jmH5',
                        apiName: 'rchText',
                        name: 'Rch text',
                        type: 'RichText',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                    ],
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'author',
                      type: 'ContentType',
                      createdAt: '2019-10-02T12:44:57.155Z',
                      updatedAt: '2020-11-06T16:28:02.610Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      revision: 2,
                    },
                    displayField: 'name',
                    description: null,
                  },
                },
                'ContentType.published.ref': {
                  _publishedVersion: true,
                  data: {
                    name: 'ref',
                    fields: [
                      {
                        id: 'GG7BV8aLkDh34J1b',
                        apiName: 'refers',
                        name: 'refers',
                        type: 'Link',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        linkType: 'Entry',
                      },
                    ],
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'ref',
                      type: 'ContentType',
                      createdAt: '2020-09-24T08:18:56.766Z',
                      updatedAt: '2020-09-24T08:18:56.766Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      revision: 1,
                    },
                    displayField: null,
                    description: '',
                  },
                },
                'ContentType.published.photoGallery': {
                  _publishedVersion: true,
                  data: {
                    name: 'Photo Gallery',
                    fields: [
                      {
                        id: 'title',
                        apiName: 'title',
                        name: 'Title',
                        type: 'Text',
                        localized: false,
                        required: true,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'slug',
                        apiName: 'slug',
                        name: 'Slug',
                        type: 'Symbol',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'author',
                        apiName: 'author',
                        name: 'Author',
                        type: 'Link',
                        localized: false,
                        required: true,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        linkType: 'Entry',
                      },
                      {
                        id: 'coverImage',
                        apiName: 'coverImage',
                        name: 'Cover Image',
                        type: 'Link',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        linkType: 'Asset',
                      },
                      {
                        id: 'description',
                        apiName: 'description',
                        name: 'Description',
                        type: 'Text',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'images',
                        apiName: 'images',
                        name: 'Images',
                        type: 'Array',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        items: {
                          type: 'Link',
                          validations: [{ linkContentType: ['image'] }],
                          linkType: 'Entry',
                        },
                      },
                      {
                        id: 'tags',
                        apiName: 'tags',
                        name: 'Tags',
                        type: 'Array',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        items: { type: 'Symbol', validations: [] },
                      },
                      {
                        id: 'date',
                        apiName: 'date',
                        name: 'Date',
                        type: 'Date',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'location',
                        apiName: 'location',
                        name: 'Location',
                        type: 'Location',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: true,
                        omitted: false,
                      },
                      {
                        id: 'p76CB85iJawX3NKM',
                        apiName: 'categories',
                        name: 'categories',
                        type: 'Array',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        items: { type: 'Link', validations: [], linkType: 'Entry' },
                      },
                    ],
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'photoGallery',
                      type: 'ContentType',
                      createdAt: '2019-10-02T12:44:57.076Z',
                      updatedAt: '2020-06-18T15:17:48.450Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      revision: 2,
                    },
                    displayField: 'title',
                    description: null,
                  },
                },
                'ContentType.published.category': {
                  _publishedVersion: true,
                  data: {
                    name: 'Category',
                    fields: [
                      {
                        id: 'gXyvzYNnWcYliYYy',
                        apiName: 'title',
                        name: 'Title',
                        type: 'Symbol',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                    ],
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'category',
                      type: 'ContentType',
                      createdAt: '2020-06-18T15:16:45.153Z',
                      updatedAt: '2020-06-18T15:16:45.153Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      revision: 1,
                    },
                    displayField: 'gXyvzYNnWcYliYYy',
                    description: '',
                  },
                },
                'ContentType.published.child': {
                  _publishedVersion: true,
                  data: {
                    name: 'Child',
                    fields: [
                      {
                        id: 'DwkvCwHn56ijfXOc',
                        apiName: 'title',
                        name: 'Title',
                        type: 'Symbol',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'OegECcVGE35OWxi6',
                        apiName: 'grandchildren',
                        name: 'Grandchildren',
                        type: 'Array',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        items: { type: 'Link', validations: [], linkType: 'Entry' },
                      },
                    ],
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'child',
                      type: 'ContentType',
                      createdAt: '2020-06-18T14:47:21.182Z',
                      updatedAt: '2020-06-18T14:47:21.182Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      revision: 1,
                    },
                    displayField: 'DwkvCwHn56ijfXOc',
                    description: '',
                  },
                },
                'ContentType.published.superSimpleTestCase': {
                  _publishedVersion: true,
                  data: {
                    name: 'SuperSimpleTestCase',
                    fields: [
                      {
                        id: 'FWhblxCNzioOlq7W',
                        apiName: 'name',
                        name: 'name',
                        type: 'Symbol',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                    ],
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'superSimpleTestCase',
                      type: 'ContentType',
                      createdAt: '2020-05-20T09:17:40.770Z',
                      updatedAt: '2020-05-20T09:17:40.770Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      revision: 1,
                    },
                    displayField: 'FWhblxCNzioOlq7W',
                    description: '',
                  },
                },
                'ContentType.published.image': {
                  _publishedVersion: true,
                  data: {
                    name: 'Image',
                    fields: [
                      {
                        id: 'title',
                        apiName: 'title',
                        name: 'Title',
                        type: 'Symbol',
                        localized: false,
                        required: true,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'photo',
                        apiName: 'photo',
                        name: 'Photo',
                        type: 'Link',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                        linkType: 'Asset',
                      },
                      {
                        id: 'imageCaption',
                        apiName: 'imageCaption',
                        name: 'Image caption',
                        type: 'Text',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                      {
                        id: 'imageCredits',
                        apiName: 'imageCredits',
                        name: 'Image credits',
                        type: 'Text',
                        localized: false,
                        required: false,
                        validations: [],
                        disabled: false,
                        omitted: false,
                      },
                    ],
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'image',
                      type: 'ContentType',
                      createdAt: '2019-10-02T12:44:57.092Z',
                      updatedAt: '2019-10-02T12:44:57.092Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      revision: 1,
                    },
                    displayField: 'title',
                    description: null,
                  },
                },
                'Asset.2x32KnbRR5pBLXcAHETvQv': {
                  persistenceContext: {
                    _baseRequest: {
                      _params: {
                        path: '/spaces/m8xyo6sh8zj8/assets',
                        headers: {},
                        putHeaders: {},
                      },
                    },
                  },
                  data: {
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: '2x32KnbRR5pBLXcAHETvQv',
                      type: 'Asset',
                      createdAt: '2020-04-06T08:53:31.263Z',
                      updatedAt: '2020-11-25T07:11:37.801Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      createdBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4ipGsNB8KSJDAbXgcekeHk' },
                      },
                      updatedBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4h9fOXzCd4aKn4aByEC5Uk' },
                      },
                      publishedCounter: 0,
                      version: 7,
                    },
                    fields: {
                      title: {
                        'en-US': 'Panthera tigris corbetti (Tierpark Berlin) 832-714-(118)',
                      },
                      file: {
                        'en-US': {
                          url: '//images.contentful.com/m8xyo6sh8zj8/2x32KnbRR5pBLXcAHETvQv/64b86217a24d3a33df1b02d5581e5477/Panthera_tigris_corbetti__Tierpark_Berlin__832-714-_118_.jpg',
                          details: { size: 2479715, image: { width: 3648, height: 2736 } },
                          fileName: 'Panthera_tigris_corbetti_(Tierpark_Berlin)_832-714-(118).jpg',
                          contentType: 'image/jpeg',
                        },
                      },
                    },
                    metadata: {
                      tags: [{ sys: { type: 'Link', linkType: 'Tag', id: 'productDesigners' } }],
                    },
                  },
                },
                'Asset.BsLDVhZSsxbbcgVwBa6lK': {
                  persistenceContext: {
                    _baseRequest: {
                      _params: {
                        path: '/spaces/m8xyo6sh8zj8/assets',
                        headers: {},
                        putHeaders: {},
                      },
                    },
                  },
                  data: {
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
                      id: 'BsLDVhZSsxbbcgVwBa6lK',
                      type: 'Asset',
                      createdAt: '2020-04-06T09:02:36.449Z',
                      updatedAt: '2020-11-25T07:11:37.830Z',
                      environment: {
                        sys: { id: 'master', type: 'Link', linkType: 'Environment' },
                      },
                      createdBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4ipGsNB8KSJDAbXgcekeHk' },
                      },
                      updatedBy: {
                        sys: { type: 'Link', linkType: 'User', id: '4h9fOXzCd4aKn4aByEC5Uk' },
                      },
                      publishedCounter: 0,
                      version: 15,
                    },
                    fields: {
                      title: {
                        'en-US': 'Orang Utan Semenggok Forest Reserve Sarawak Borneo Malaysia',
                      },
                      description: { 'en-US': 'asdfasdfasdfasdfasfasfasdf' },
                      file: {
                        'en-US': {
                          url: '//images.contentful.com/m8xyo6sh8zj8/BsLDVhZSsxbbcgVwBa6lK/7032ecc5431bdbfe7737b01f21556716/orangutan.jpg',
                          details: { size: 1443340, image: { width: 1558, height: 2251 } },
                          fileName:
                            'Orang_Utan_Semenggok_Forest_Reserve_Sarawak_Borneo_Malaysia.JPG',
                          contentType: 'image/jpeg',
                        },
                      },
                    },
                    metadata: {
                      tags: [
                        {
                          sys: {
                            type: 'Link',
                            linkType: 'Tag',
                            id: 'anotherHopefullyUnchangeableAccessTag',
                          },
                        },
                        { sys: { type: 'Link', linkType: 'Tag', id: 'asdfdsfsdfdsf' } },
                        { sys: { type: 'Link', linkType: 'Tag', id: 'halloP' } },
                        { sys: { type: 'Link', linkType: 'Tag', id: 'helloTaggy' } },
                        { sys: { type: 'Link', linkType: 'Tag', id: 'moreTesting' } },
                        { sys: { type: 'Link', linkType: 'Tag', id: 'productDesigners' } },
                        { sys: { type: 'Link', linkType: 'Tag', id: 'testjanko2' } },
                      ],
                    },
                  },
                },
              },
            },
          },
          data: {
            sys: {
              space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
              id: '2JA7S5tIHhz2XqKEEsOkrw',
              type: 'Entry',
              createdAt: '2020-11-18T11:45:47.563Z',
              updatedAt: '2020-11-18T15:00:51.998Z',
              environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
              createdBy: {
                sys: { type: 'Link', linkType: 'User', id: '4YpDH9qCqCs7OLClBfZuvD' },
              },
              updatedBy: {
                sys: { type: 'Link', linkType: 'User', id: '0Wqpu0iURWIzkfkG7a4pKb' },
              },
              publishedCounter: 0,
              version: 4,
              contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'author' } },
            },
            fields: {
              name: { 'en-US': 'l ökm ökmö' },
              twitterHandle: { 'en-US': 'lm,lölmölmö' },
            },
            metadata: { tags: [{ sys: { type: 'Link', linkType: 'Tag', id: 'accessTagType' } }] },
          },
        },
        entityInfo: {
          id: '2JA7S5tIHhz2XqKEEsOkrw',
          type: 'Entry',
          contentTypeId: 'author',
          contentType: {
            name: 'Author',
            fields: [
              {
                id: 'name',
                apiName: 'name',
                name: 'Name',
                type: 'Symbol',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
              {
                id: 'twitterHandle',
                apiName: 'twitterHandle',
                name: 'Twitter handle',
                type: 'Symbol',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
              {
                id: 'profilePhoto',
                apiName: 'profilePhoto',
                name: 'Profile photo',
                type: 'Link',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
                linkType: 'Asset',
              },
              {
                id: 'biography',
                apiName: 'biography',
                name: 'Biography',
                type: 'Text',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
              {
                id: 'createdEntries',
                apiName: 'createdEntries',
                name: 'Created entries',
                type: 'Array',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
                items: {
                  type: 'Link',
                  validations: [{ linkContentType: ['image'] }],
                  linkType: 'Entry',
                },
              },
              {
                id: 'DlBLCNlzGFA0jmH5',
                apiName: 'rchText',
                name: 'Rch text',
                type: 'RichText',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
            ],
            sys: {
              space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
              id: 'author',
              type: 'ContentType',
              createdAt: '2019-10-02T12:44:57.155Z',
              updatedAt: '2020-11-06T16:28:02.610Z',
              environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
              revision: 2,
            },
            displayField: 'name',
            description: null,
          },
        },
        editorInterface: {
          sys: {
            id: 'default',
            type: 'EditorInterface',
            space: { sys: { id: 'm8xyo6sh8zj8', type: 'Link', linkType: 'Space' } },
            version: 3,
            createdAt: '2019-10-02T12:44:57.381Z',
            createdBy: { sys: { id: '4h9fOXzCd4aKn4aByEC5Uk', type: 'Link', linkType: 'User' } },
            updatedAt: '2020-11-06T16:28:04.854Z',
            updatedBy: { sys: { id: '4ipGsNB8KSJDAbXgcekeHk', type: 'Link', linkType: 'User' } },
            contentType: { sys: { id: 'author', type: 'Link', linkType: 'ContentType' } },
            environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
          },
          controls: [
            {
              fieldId: 'name',
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'name',
                apiName: 'name',
                name: 'Name',
                type: 'Symbol',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
            },
            {
              fieldId: 'twitterHandle',
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'twitterHandle',
                apiName: 'twitterHandle',
                name: 'Twitter handle',
                type: 'Symbol',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
            },
            {
              fieldId: 'profilePhoto',
              widgetId: 'assetLinkEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'profilePhoto',
                apiName: 'profilePhoto',
                name: 'Profile photo',
                type: 'Link',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
                linkType: 'Asset',
              },
            },
            {
              fieldId: 'biography',
              widgetId: 'markdown',
              widgetNamespace: 'builtin',
              field: {
                id: 'biography',
                apiName: 'biography',
                name: 'Biography',
                type: 'Text',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
            },
            {
              fieldId: 'createdEntries',
              widgetId: 'entryLinksEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'createdEntries',
                apiName: 'createdEntries',
                name: 'Created entries',
                type: 'Array',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
                items: {
                  type: 'Link',
                  validations: [{ linkContentType: ['image'] }],
                  linkType: 'Entry',
                },
              },
            },
            {
              fieldId: 'rchText',
              widgetId: 'richTextEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'DlBLCNlzGFA0jmH5',
                apiName: 'rchText',
                name: 'Rch text',
                type: 'RichText',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
            },
          ],
          editors: [],
        },
        widgetTrackingContexts: [
          {
            schema: 'iglu:com.contentful/sidebar_render/jsonschema/1-0-0',
            data: { is_default: true, has_legacy_extensions: false, widgets: null },
          },
        ],
        fieldControls: {
          sidebar: [],
          form: [
            {
              fieldId: 'name',
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'name',
                apiName: 'name',
                name: 'Name',
                type: 'Symbol',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
              descriptor: {
                fieldTypes: ['Text', 'Symbol'],
                name: 'Single line',
                icon: 'singleline',
                id: 'singleLine',
                namespace: 'builtin',
                parameters: [
                  {
                    id: 'helpText',
                    name: 'Help text',
                    type: 'Symbol',
                    description: 'This help text will show up below the field',
                  },
                ],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'twitterHandle',
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'twitterHandle',
                apiName: 'twitterHandle',
                name: 'Twitter handle',
                type: 'Symbol',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'profilePhoto',
              widgetId: 'assetLinkEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'profilePhoto',
                apiName: 'profilePhoto',
                name: 'Profile photo',
                type: 'Link',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
                linkType: 'Asset',
              },
              descriptor: {
                fieldTypes: ['Asset'],
                name: 'Asset card',
                icon: 'media-preview',
                parameters: [
                  null,
                  {
                    id: 'showCreateEntityAction',
                    name: 'Show "Create new assets"',
                    description:
                      'When enabled, people can create and link new assets (based on user permissions)',
                    type: 'Boolean',
                    default: true,
                  },
                  {
                    id: 'showLinkEntityAction',
                    name: 'Show "Link existing assets"',
                    description:
                      'When enabled, people can link existing assets (based on user permissions)',
                    type: 'Boolean',
                    default: true,
                  },
                ],
                id: 'assetLinkEditor',
                namespace: 'builtin',
              },
              settings: { showCreateEntityAction: true, showLinkEntityAction: true },
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'biography',
              widgetId: 'markdown',
              widgetNamespace: 'builtin',
              field: {
                id: 'biography',
                apiName: 'biography',
                name: 'Biography',
                type: 'Text',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
              descriptor: {
                fieldTypes: ['Text'],
                name: 'Markdown',
                icon: 'markdown',
                id: 'markdown',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'createdEntries',
              widgetId: 'entryLinksEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'createdEntries',
                apiName: 'createdEntries',
                name: 'Created entries',
                type: 'Array',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
                items: {
                  type: 'Link',
                  validations: [{ linkContentType: ['image'] }],
                  linkType: 'Entry',
                },
              },
              descriptor: {
                fieldTypes: ['Entries'],
                name: 'Entry links list',
                icon: 'references',
                parameters: [
                  null,
                  {
                    id: 'bulkEditing',
                    name: 'Use bulk editing',
                    description: 'Ideal for entries with only a few fields',
                    type: 'Boolean',
                    default: false,
                  },
                  {
                    id: 'showCreateEntityAction',
                    name: 'Show "Create new entries"',
                    description:
                      'When enabled, people can create and link new entries (based on user permissions)',
                    type: 'Boolean',
                    default: true,
                  },
                  {
                    id: 'showLinkEntityAction',
                    name: 'Show "Link existing entries"',
                    description:
                      'When enabled, people can link existing entries (based on user permissions)',
                    type: 'Boolean',
                    default: true,
                  },
                ],
                id: 'entryLinksEditor',
                namespace: 'builtin',
              },
              settings: {
                bulkEditing: false,
                showCreateEntityAction: true,
                showLinkEntityAction: true,
              },
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'rchText',
              widgetId: 'richTextEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'DlBLCNlzGFA0jmH5',
                apiName: 'rchText',
                name: 'Rch text',
                type: 'RichText',
                localized: false,
                required: false,
                validations: [],
                disabled: false,
                omitted: false,
              },
              descriptor: {
                fieldTypes: ['RichText'],
                name: 'RichText',
                icon: 'wysiwig',
                id: 'richTextEditor',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
          ],
          all: [null, null, null, null, null, null],
        },
        sidebarExtensions: [],
        editorsExtensions: [
          {
            widgetId: 'default-editor',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'Editor',
              id: 'default-editor',
              icon: 'Entry',
            },
            parameters: { instance: {}, installation: {} },
          },
          {
            widgetId: 'reference-tree',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'References',
              id: 'reference-tree',
              icon: 'References',
            },
            parameters: { instance: {}, installation: {} },
          },
          {
            widgetId: 'tags-editor',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'Tags',
              id: 'tags-editor',
              icon: 'Tags',
            },
            parameters: { instance: {}, installation: {} },
          },
        ],
      },
    },
    Asset: {
      '2x32KnbRR5pBLXcAHETvQv': {
        contentType: {
          data: {
            sys: { type: 'AssetContentType' },
            fields: [
              { id: 'title', name: 'Title', type: 'Symbol', localized: true, disabled: false },
              {
                id: 'description',
                name: 'Description',
                type: 'Text',
                localized: true,
                disabled: false,
              },
              {
                id: 'file',
                name: 'File',
                type: 'File',
                localized: true,
                disabled: false,
                required: true,
              },
            ],
          },
        },
        entityInfo: {
          id: '2x32KnbRR5pBLXcAHETvQv',
          type: 'Asset',
          contentType: {
            sys: { type: 'AssetContentType' },
            fields: [
              { id: 'title', name: 'Title', type: 'Symbol', localized: true, disabled: false },
              {
                id: 'description',
                name: 'Description',
                type: 'Text',
                localized: true,
                disabled: false,
              },
              {
                id: 'file',
                name: 'File',
                type: 'File',
                localized: true,
                disabled: false,
                required: true,
              },
            ],
          },
        },
        editorInterface: {
          sys: {
            type: 'EditorInterface',
            contentType: { sys: { type: 'Link', linkType: 'ContentType' } },
          },
          controls: [
            {
              fieldId: 'title',
              field: {
                id: 'title',
                name: 'Title',
                type: 'Symbol',
                localized: true,
                disabled: false,
              },
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
            },
            {
              fieldId: 'description',
              widgetId: 'multipleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'description',
                name: 'Description',
                type: 'Text',
                localized: true,
                disabled: false,
              },
            },
            {
              fieldId: 'file',
              field: {
                id: 'file',
                name: 'File',
                type: 'File',
                localized: true,
                disabled: false,
                required: true,
              },
              widgetId: 'fileEditor',
              widgetNamespace: 'builtin',
            },
          ],
          editors: [],
        },
        widgetTrackingContexts: [
          {
            schema: 'iglu:com.contentful/sidebar_render/jsonschema/1-0-0',
            data: { is_default: true, has_legacy_extensions: false, widgets: null },
          },
        ],
        fieldControls: {
          sidebar: [],
          form: [
            {
              fieldId: 'title',
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'title',
                name: 'Title',
                type: 'Symbol',
                localized: true,
                disabled: false,
              },
              descriptor: {
                fieldTypes: ['Text', 'Symbol'],
                name: 'Single line',
                icon: 'singleline',
                id: 'singleLine',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'description',
              widgetId: 'multipleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'description',
                name: 'Description',
                type: 'Text',
                localized: true,
                disabled: false,
              },
              descriptor: {
                fieldTypes: ['Text'],
                name: 'Multiple line',
                icon: 'multipleline',
                id: 'multipleLine',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'file',
              widgetId: 'fileEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'file',
                name: 'File',
                type: 'File',
                localized: true,
                disabled: false,
                required: true,
              },
              descriptor: {
                fieldTypes: ['File'],
                name: 'File',
                id: 'fileEditor',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
          ],
          all: [null, null, null],
        },
        sidebarExtensions: [],
        editorsExtensions: [
          {
            widgetId: 'default-editor',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'Editor',
              id: 'default-editor',
              icon: 'Entry',
            },
            parameters: { instance: {}, installation: {} },
          },
          {
            widgetId: 'reference-tree',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'References',
              id: 'reference-tree',
              icon: 'References',
            },
            parameters: { instance: {}, installation: {} },
          },
          {
            widgetId: 'tags-editor',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'Tags',
              id: 'tags-editor',
              icon: 'Tags',
            },
            parameters: { instance: {}, installation: {} },
          },
        ],
      },
      BsLDVhZSsxbbcgVwBa6lK: {
        entityInfo: {
          id: 'BsLDVhZSsxbbcgVwBa6lK',
          type: 'Asset',
          contentType: {
            sys: { type: 'AssetContentType' },
            fields: [
              { id: 'title', name: 'Title', type: 'Symbol', localized: true, disabled: false },
              {
                id: 'description',
                name: 'Description',
                type: 'Text',
                localized: true,
                disabled: false,
              },
              {
                id: 'file',
                name: 'File',
                type: 'File',
                localized: true,
                disabled: false,
                required: true,
              },
            ],
          },
        },
        editorInterface: {
          sys: {
            type: 'EditorInterface',
            contentType: { sys: { type: 'Link', linkType: 'ContentType' } },
          },
          controls: [
            {
              fieldId: 'title',
              field: {
                id: 'title',
                name: 'Title',
                type: 'Symbol',
                localized: true,
                disabled: false,
              },
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
            },
            {
              fieldId: 'description',
              widgetId: 'multipleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'description',
                name: 'Description',
                type: 'Text',
                localized: true,
                disabled: false,
              },
            },
            {
              fieldId: 'file',
              field: {
                id: 'file',
                name: 'File',
                type: 'File',
                localized: true,
                disabled: false,
                required: true,
              },
              widgetId: 'fileEditor',
              widgetNamespace: 'builtin',
            },
          ],
        },
        widgetTrackingContexts: [
          {
            schema: 'iglu:com.contentful/sidebar_render/jsonschema/1-0-0',
            data: { is_default: true, has_legacy_extensions: false, widgets: null },
          },
        ],
        fieldControls: {
          sidebar: [],
          form: [
            {
              fieldId: 'title',
              widgetId: 'singleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'title',
                name: 'Title',
                type: 'Symbol',
                localized: true,
                disabled: false,
              },
              descriptor: {
                fieldTypes: ['Text', 'Symbol'],
                name: 'Single line',
                icon: 'singleline',
                id: 'singleLine',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'description',
              widgetId: 'multipleLine',
              widgetNamespace: 'builtin',
              field: {
                id: 'description',
                name: 'Description',
                type: 'Text',
                localized: true,
                disabled: false,
              },
              descriptor: {
                fieldTypes: ['Text'],
                name: 'Multiple line',
                icon: 'multipleline',
                id: 'multipleLine',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
            {
              fieldId: 'file',
              widgetId: 'fileEditor',
              widgetNamespace: 'builtin',
              field: {
                id: 'file',
                name: 'File',
                type: 'File',
                localized: true,
                disabled: false,
                required: true,
              },
              descriptor: {
                fieldTypes: ['File'],
                name: 'File',
                id: 'fileEditor',
                namespace: 'builtin',
                parameters: [null],
              },
              settings: {},
              parameters: { installation: {} },
              isFocusable: true,
              sidebar: false,
            },
          ],
          all: [null, null, null],
        },
        sidebarExtensions: [],
        editorsExtensions: [
          {
            widgetId: 'default-editor',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'Editor',
              id: 'default-editor',
              icon: 'Entry',
            },
            parameters: { instance: {}, installation: {} },
          },
          {
            widgetId: 'reference-tree',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'References',
              id: 'reference-tree',
              icon: 'References',
            },
            parameters: { instance: {}, installation: {} },
          },
          {
            widgetId: 'tags-editor',
            widgetNamespace: 'editor-builtin',
            disabled: false,
            descriptor: {
              namespace: 'editor-builtin',
              name: 'Tags',
              id: 'tags-editor',
              icon: 'Tags',
            },
            parameters: { instance: {}, installation: {} },
          },
        ],
      },
    },
  },
  contentTypes: [
    {
      name: 'Author',
      fields: [
        {
          id: 'name',
          apiName: 'name',
          name: 'Name',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'twitterHandle',
          apiName: 'twitterHandle',
          name: 'Twitter handle',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'profilePhoto',
          apiName: 'profilePhoto',
          name: 'Profile photo',
          type: 'Link',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
        {
          id: 'biography',
          apiName: 'biography',
          name: 'Biography',
          type: 'Text',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'createdEntries',
          apiName: 'createdEntries',
          name: 'Created entries',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['image'] }],
            linkType: 'Entry',
          },
        },
      ],
      sys: {
        space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
        id: 'author',
        type: 'ContentType',
        createdAt: '2019-10-02T12:44:57.155Z',
        updatedAt: '2020-11-06T16:28:02.610Z',
        environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
        revision: 2,
      },
      displayField: 'name',
      description: null,
    },
    {
      name: 'Category',
      fields: [
        {
          id: 'gXyvzYNnWcYliYYy',
          apiName: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
      ],
      sys: {
        space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
        id: 'category',
        type: 'ContentType',
        createdAt: '2020-06-18T15:16:45.153Z',
        updatedAt: '2020-06-18T15:16:45.153Z',
        environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
        revision: 1,
      },
      displayField: 'gXyvzYNnWcYliYYy',
      description: '',
    },
    {
      name: 'Image',
      fields: [
        {
          id: 'title',
          apiName: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'photo',
          apiName: 'photo',
          name: 'Photo',
          type: 'Link',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
        {
          id: 'imageCaption',
          apiName: 'imageCaption',
          name: 'Image caption',
          type: 'Text',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'imageCredits',
          apiName: 'imageCredits',
          name: 'Image credits',
          type: 'Text',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
      ],
      sys: {
        space: { sys: { type: 'Link', linkType: 'Space', id: 'm8xyo6sh8zj8' } },
        id: 'image',
        type: 'ContentType',
        createdAt: '2019-10-02T12:44:57.092Z',
        updatedAt: '2019-10-02T12:44:57.092Z',
        environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
        revision: 1,
      },
      displayField: 'title',
      description: null,
    },
  ],
};
