const SET_REFERENCES = 'SET_REFERENCES';
const SET_LINKS_COUNTER = 'SET_LINKS_COUNTER';
const SET_SELECTED_ENTITIES = 'SET_SELECTED_ENTITIES';
const SET_VALIDATIONS = 'SET_VALIDATIONS';
const SET_MAX_DEPTH_REACHED = 'SET_TOO_COMPLEX';
const SET_ACTIONS_DISABLED = 'SET_ACTIONS_DISABLED';
const SET_INITIAL_REFERENCES_AMOUNT = 'SET_INITIAL_REFERENCES_AMOUNT';
const SET_REFERENCE_TREE_KEY = 'SET_REFERENCE_TREE_KEY';
const SET_IS_TOO_COMPLEX = 'SET_IS_TOO_COMPLEX';

export {
  SET_REFERENCES,
  SET_LINKS_COUNTER,
  SET_SELECTED_ENTITIES,
  SET_VALIDATIONS,
  SET_MAX_DEPTH_REACHED,
  SET_ACTIONS_DISABLED,
  SET_INITIAL_REFERENCES_AMOUNT,
  SET_REFERENCE_TREE_KEY,
  SET_IS_TOO_COMPLEX,
};
