module.exports = {
  plugins: ['jest', 'rulesdir'],
  // todo: enable and fix all errors and warnings
  // extends: ['plugin:jest/recommended', 'plugin:jest/style'],
  rules: {
    'rulesdir/relative-imports': 'off',
    'import/no-unresolved': 'off',
    'jest/no-disabled-tests': 'warn',
    'jest/no-focused-tests': 'error',
    'jest/no-identical-title': 'error',
    'jest/no-jest-import': 'warn',
    'jest/prefer-to-have-length': 'warn',
    'jest/valid-expect': 'error',
    'jest/consistent-test-it': ['warn', { fn: 'it' }],
    'jest/no-jasmine-globals': 'warn',
    'jest/no-test-prefixes': 'error',
    'jest/prefer-to-be-null': 'warn',
    'jest/prefer-to-be-undefined': 'warn',
    'rulesdir/restrict-sinon': 'error',
    'rulesdir/restrict-virtual-true': 'error',
    'react/prop-types': 'off',
  },
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module',
  },
  globals: {
    describe: true,
    it: true,
    test: true,
    expect: true,
    jest: true,
    spy: true,
    beforeEach: true,
    afterEach: true,
    beforeAll: true,
    afterAll: true,
  },
};
