version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    target_branch: 'master'
    default_labels:
      - 'dependencies'
      - 'dependabot'
    allowed_updates:
      - match:
          update_type: 'security'
    ignored_updates:
      - match:
          dependency_name: 'angular*'
    commit_message:
      prefix: 'chore'
