const SET_RELEASES_INCLUDING_ENTRY = 'SET_RELEASES_INCLUDING_ENTRY';
const SET_RELEASE_ENTITIES = 'SET_RELEASE_ENTITIES';
const SET_RELEASE_VALIDATIONS = 'SET_RELEASE_VALIDATIONS';
const SET_RELEASE_ENTITIES_LOADING = 'SET_RELEASE_ENTITIES_LOADING';
const SET_RELEASE_LIST_SELECTED_TAB = 'SET_RELEASE_LIST_SELECTED_TAB';
const SET_RELEASE_PROCESSING_ACTION = 'SET_RELEASE_PROCESSING_ACTION';

export {
  SET_RELEASES_INCLUDING_ENTRY,
  SET_RELEASE_ENTITIES,
  SET_RELEASE_VALIDATIONS,
  SET_RELEASE_ENTITIES_LOADING,
  SET_RELEASE_LIST_SELECTED_TAB,
  SET_RELEASE_PROCESSING_ACTION,
};
